name: Integração Contínua

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configuração do Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # 3. Instalação de dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Execução dos testes
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=src
